### ISSUE TITLE
Open browser on start

### ISSUE THREAD

**Issue by shyim** [shyim/php-dump-server#4]

**Comment by mitelg** [comment]
it would also be nice, if there is some feedback, if I click on the executable on Linux. nothing seems to happen. but if I open "htop", I can see that it is up and running

**Comment by aragon999** [comment]
With the commit f234560 when clicking on the executable the browser should launch and the server should only be started once, and on another click on the executable should only open the browser.
Since I have only Linux for now only Linux is tested :-)
